### ISSUE TITLE
The modules package and requirements.txt are missing

### ISSUE THREAD

**Issue by tt1207tt** [Jiwonjeon9603/MASER#1]
hello！
Running error, missing something
The modules package and requirements.txt are missing
Can you supplement the full version of the code? Thank you very much！！！

**Comment by Jiwonjeon9603** [comment]
Hello! Thanks for your interest.

I uploaded requirements.txt, so please check it.

If you have any questions, please let me know.

**Comment by tt1207tt** [comment]
Hello, thank you very much for your response.
Vdn and qmix are missing from the modules package. 
No module named 'modules.mixers.vdn'and‘No module named 'modules.mixers.qmix'
Is it convenient to supplement them? thank you!

**Comment by bbqp0313** [comment]
Thanks for uploading requirements.txt
but there are still missing files in modules package(ie. agent and mixer)
Can you supplement these files?

**Comment by Isaac009** [comment]
When it's about to install the following package
cffi @ file:///tmp/build/80754af9/cffi_1625814693446/work

I get the error below:
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 101, in __init__
    raise InvalidRequirement("Invalid URL given")
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL given

Could you please help us to resolve this issue?
We will appreciate it.

**Comment by Jiwonjeon9603** [comment]
> Thanks for uploading requirements.txt but there are still missing files in modules package(ie. agent and mixer) Can you supplement these files?

Hello, sorry for late answer.
I uploaded modules package!

Thanks

**Comment by Jiwonjeon9603** [comment]
> When it's about to install the following package cffi @ file:///tmp/build/80754af9/cffi_1625814693446/work
> 
> I get the error below: ERROR: Exception: Traceback (most recent call last): File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/**init**.py", line 3101, in **init** super(Requirement, self).**init**(requirement_string) File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 101, in **init** raise InvalidRequirement("Invalid URL given") pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL given
> 
> Could you please help us to resolve this issue? We will appreciate it.

Hi,

I think you should install the package following with this webpage.
- https://github.com/oxwhirl/smac
 
If you have more question, please reply to me :)

**Comment by Isaac009** [comment]
> > When it's about to install the following package cffi @ file:///tmp/build/80754af9/cffi_1625814693446/work
> > I get the error below: ERROR: Exception: Traceback (most recent call last): File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/**init**.py", line 3101, in **init** super(Requirement, self).**init**(requirement_string) File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 101, in **init** raise InvalidRequirement("Invalid URL given") pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL given
> > Could you please help us to resolve this issue? We will appreciate it.
> 
> Hi,
> 
> I think you should install the package following with this webpage.
> 
> * https://github.com/oxwhirl/smac
> 
> If you have more question, please reply to me :)

Thank you!! It seems to go somewhere, but I hit this error again, 

[ERROR 17:27:12] pymarl Failed after 0:00:00!
Traceback (most recent call last):
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "main.py", line 36, in my_main
    run(_run, config, _log)
  File "user_home/Documents/research/MARL/MASER/run.py", line 52, in run
    run_sequential(args=args, logger=logger)
  File "user_home/Documents/research/MARL/MASER/run.py", line 86, in run_sequential
    env_info = runner.get_env_info()
  File "user_home/Documents/research/MARL/MASER/runners/episode_runner.py", line 38, in get_env_info
    return self.env.get_env_info()
  File "user_home/Documents/research/MARL/MASER/envs/multiagentenv.py", line 73, in get_env_info
    "units_type_id": self.get_units_type_id(),
  File "user_home/Documents/research/MARL/MASER/envs/starcraft2/starcraft2.py", line 824, in get_units_type_id
    self.reset()
  File "user_home/Documents/research/MARL/MASER/envs/starcraft2/starcraft2.py", line 348, in reset
    self._launch()
  File "user_home/Documents/research/MARL/MASER/envs/starcraft2/starcraft2.py", line 293, in _launch
    self._run_config = run_configs.get()
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/pysc2/run_configs/platforms.py", line 57, in __init__
    super(LocalBase, self).__init__(
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "user_home/python_envs/MASER_ENV/lib/python3.8/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'user_home/Documents/research/MARL/MASER/3rdparty/StarCraftII/Versions'

Having issues when MASER tries to locate 3rdparty/StarCraftII/Versions

Following instructions on [smac installation](https://github.com/oxwhirl/smac) the packages were install here: user_home/StarCraftII
and the version could easily located here: user_home/StarCraftII/Versions/Base75689/SC2_x64

Do I have to install StarCraftII to MASER/3rdparty for it to work properly or 
Could you suggest how to configure the path or installation in such a way that the sacred can easily locate the required file/directory?

**Comment by Jiwonjeon9603** [comment]
Hello!

You need to move StarCraft2 folder which you installed in  user_home/StarCraftII to 'user_home/Documents/research/MARL/MASER/3rdparty/StarCraftII/' this location.

If you have more issues, please contact to my e-mail address. I will share a full code.

Thanks :)

**Comment by Isaac009** [comment]
> Hello!
> 
> You need to move StarCraft2 folder which you installed in user_home/StarCraftII to 'user_home/Documents/research/MARL/MASER/3rdparty/StarCraftII/' this location.
> 
> If you have more issues, please contact to my e-mail address. I will share a full code.
> 
> Thanks :)

This solution solved the problem.
Thanks a lot. Everything works fine now.
