### ISSUE TITLE
Is it possible that some packages are missing?

### ISSUE THREAD

**Issue by codefarmer2** [Jiwonjeon9603/MASER#5]
Hello！
I followed the steps and encountered the following error when running the example. Is it possible that some packages are missing? Thank you very much.

[DEBUG 20:40:46] git.cmd Popen(['git', 'version'], cwd=/mnt/workspace/multi-agent/MASER, universal_newlines=False, shell=None, istream=None)
[DEBUG 20:40:46] git.cmd Popen(['git', 'version'], cwd=/mnt/workspace/multi-agent/MASER, universal_newlines=False, shell=None, istream=None)
[DEBUG 20:40:46] git.util Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'No such file or directory')
[DEBUG 20:40:46] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/mnt/workspace/multi-agent, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/home/pai/envs/py38/lib/python3.8/site-packages/sacred/experiment.py", line 119, in __init__
    super().__init__(
  File "/home/pai/envs/py38/lib/python3.8/site-packages/sacred/ingredient.py", line 75, in __init__
    ) = gather_sources_and_dependencies(
  File "/home/pai/envs/py38/lib/python3.8/site-packages/sacred/dependencies.py", line 725, in gather_sources_and_dependencies
    experiment_path, main = get_main_file(globs, save_git_info)
  File "/home/pai/envs/py38/lib/python3.8/site-packages/sacred/dependencies.py", line 596, in get_main_file
    main = Source.create(globs.get("__file__"), save_git_info)
  File "/home/pai/envs/py38/lib/python3.8/site-packages/sacred/dependencies.py", line 460, in create
    repo, commit, is_dirty = get_commit_if_possible(main_file, save_git_info)
  File "/home/pai/envs/py38/lib/python3.8/site-packages/sacred/dependencies.py", line 440, in get_commit_if_possible
    is_dirty = repo.is_dirty()
  File "/home/pai/envs/py38/lib/python3.8/site-packages/git/repo/base.py", line 819, in is_dirty
    if osp.isfile(self.index.path) and len(self.git.diff("--cached", *default_args)):
  File "/home/pai/envs/py38/lib/python3.8/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/pai/envs/py38/lib/python3.8/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/pai/envs/py38/lib/python3.8/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw
  stderr: 'error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>

**Comment by Jiwonjeon9603** [comment]
Can you tell me which packages are missing?
